// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rtruncnorm_plain_cpp
arma::vec rtruncnorm_plain_cpp(int n, arma::vec mean, arma::vec sd, double lb, double ub);
RcppExport SEXP _BayesRank_rtruncnorm_plain_cpp(SEXP nSEXP, SEXP meanSEXP, SEXP sdSEXP, SEXP lbSEXP, SEXP ubSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type sd(sdSEXP);
    Rcpp::traits::input_parameter< double >::type lb(lbSEXP);
    Rcpp::traits::input_parameter< double >::type ub(ubSEXP);
    rcpp_result_gen = Rcpp::wrap(rtruncnorm_plain_cpp(n, mean, sd, lb, ub));
    return rcpp_result_gen;
END_RCPP
}
// sample_MVTN_gibbs_cpp
arma::mat sample_MVTN_gibbs_cpp(arma::mat Z_m, arma::mat Z_mean_m, arma::vec muC_m, arma::vec rho2_m, arma::vec sd_m, double lb_h, double ub_h, int n_iter);
RcppExport SEXP _BayesRank_sample_MVTN_gibbs_cpp(SEXP Z_mSEXP, SEXP Z_mean_mSEXP, SEXP muC_mSEXP, SEXP rho2_mSEXP, SEXP sd_mSEXP, SEXP lb_hSEXP, SEXP ub_hSEXP, SEXP n_iterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Z_m(Z_mSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Z_mean_m(Z_mean_mSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type muC_m(muC_mSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type rho2_m(rho2_mSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type sd_m(sd_mSEXP);
    Rcpp::traits::input_parameter< double >::type lb_h(lb_hSEXP);
    Rcpp::traits::input_parameter< double >::type ub_h(ub_hSEXP);
    Rcpp::traits::input_parameter< int >::type n_iter(n_iterSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_MVTN_gibbs_cpp(Z_m, Z_mean_m, muC_m, rho2_m, sd_m, lb_h, ub_h, n_iter));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_BayesRank_rtruncnorm_plain_cpp", (DL_FUNC) &_BayesRank_rtruncnorm_plain_cpp, 5},
    {"_BayesRank_sample_MVTN_gibbs_cpp", (DL_FUNC) &_BayesRank_sample_MVTN_gibbs_cpp, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_BayesRank(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
