# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Vectorized sampling from univariate truncated normal distributions (inverse-CDF method)
#'
#' @param n Number of draws.
#' @param mean Vector of means of the underlying normal.
#' @param sd Vector of SDs of the underlying normal.
#' @param lb Lower truncation bound.
#' @param ub Upper truncation bound.
#'
#' @return Numeric vector of length n.
#'
#' @noRd
#' 
rtruncnorm_plain_cpp <- function(n, mean, sd, lb, ub) {
    .Call(`_BayesRank_rtruncnorm_plain_cpp`, n, mean, sd, lb, ub)
}

#' Vectorized sampling from multivariate truncated normal distributions
#'
#' Updates a block of correlated truncated-normal latent utilities,
#' by updating one coordinate at a time via inner Gibbs sampling sweeps.
#'
#' @param Z_m Matrix of current latent utility values for the group.
#' @param Z_mean_m Matrix of conditional means.
#' @param muC_m Conditioning adjustment term from the marginalized random effect.
#' @param rho2_m Random-effect variance term for this group size.
#' @param sd_m Conditional SD for the truncated normal draws.
#' @param lb_h,ub_h Truncation bounds (ordinal category cutoffs).
#' @param n_iter Number of inner Gibbs sweeps.
#'
#' @return Updated matrix of latent utility values, same shape as Z_m.
#'
#' @noRd
#' 
sample_MVTN_gibbs_cpp <- function(Z_m, Z_mean_m, muC_m, rho2_m, sd_m, lb_h, ub_h, n_iter) {
    .Call(`_BayesRank_sample_MVTN_gibbs_cpp`, Z_m, Z_mean_m, muC_m, rho2_m, sd_m, lb_h, ub_h, n_iter)
}

